sudo: false

language: node_js

node_js:
  - "node"

os:
  - linux
  - osx

matrix:
  include:
    - env: CODE_VERSION=1.17.2
    - env: CODE_VERSION=1.18.1
    - env: CODE_VERSION=1.19.3
    - env: CODE_VERSION=insiders
  allow_failures:
    - env: CODE_VERSION=insiders

cache:
  directories:
    - "node_modules"

before_install:
  - if [ $TRAVIS_OS_NAME == "linux" ]; then
      export CXX="g++-4.9" CC="gcc-4.9" DISPLAY=:99.0;
      sh -e /etc/init.d/xvfb start;
      sleep 3;
    fi

install:
  - npm install
#- npm run prettier
  - npm run vscode:prepublish
  # For coverage
  - sed -i.bak 's/"\*"//g' package.json

script:
  - npm test --silent

after_success:
  - bash <(curl -s https://codecov.io/bash)
