environment:
  ELECTRON_RUN_AS_NODE: 1
  VSCODE_BUILD_VERBOSE: true

cache:
  - '%LOCALAPPDATA%\Yarn\cache'

install:
  - ps: Install-Product node 8.9.1 x64

build_script:
  - npm install
  - .\node_modules\.bin\gulp electron
  - npm run compile
  - npm run vscode:prepublish

test_script:
  - npm run prettier
  - npm run test --silent